# Generated by Django 5.0.4 on 2024-09-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_return', models.BooleanField(default=False, verbose_name='نمونه برگشت داده شده بشود')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faculty_member', models.BooleanField(default=False)),
                ('is_student_or_staff', models.BooleanField(default=False)),
                ('is_affiliated_with_institution', models.BooleanField(default=False)),
                ('discount_institution_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('vacuum_oven', 'Vacuum Oven'), ('oven', 'Oven'), ('sieve_sample', 'نمونه دانه بندی (الک)')], max_length=50, verbose_name='نوع نمونه')),
                ('sample_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار نمونه')),
                ('sample_unit', models.CharField(choices=[('KG', 'کیلوگرم'), ('G', 'گرم'), ('MG', 'میلی\u200cگرم'), ('LB', 'پوند'), ('OZ', 'اونس')], max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='نمونه فاسدشدنی است')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('storage_duration', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)')),
                ('storage_unit', models.CharField(choices=[('D', 'روز'), ('W', 'هفته'), ('M', 'ماه')], max_length=10, verbose_name='واحد مدت زمان نگهداری')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='orders.cost', verbose_name='درخواست')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='orders.additionalinfo', verbose_name='اطلاعات اضافی')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='orders.cost', verbose_name='هزینه')),
                ('discount_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='orders.discountinfo', verbose_name='تخفیف')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdditionalInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.additionalinfo', verbose_name='اطلاعات تکمیلی')),
                ('ExperimentInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.experimentinfo', verbose_name='اطلاعات آزمایش')),
                ('RequestInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.requestinfo', verbose_name='اطلاعات درخواست')),
                ('SampleInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.sampleinfo', verbose_name='اطلاعات نمونه')),
            ],
        ),
    ]
