# Generated by Django 5.1.1 on 2025-01-05 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryorder',
            name='discount_info',
        ),
        migrations.RemoveField(
            model_name='temporaryorder',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='temporaryorder',
            name='request_info',
        ),
        migrations.RemoveField(
            model_name='temporaryorder',
            name='sample_info',
        ),
        migrations.RemoveField(
            model_name='temporaryorder',
            name='test_info',
        ),
        migrations.RemoveField(
            model_name='temporaryorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporaryrequestinfo',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='temporaryrequestinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporarysampleinfo',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='temporarysampleinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporarytestinfo',
            name='user_sample',
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='user_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sampleinfo', verbose_name='شناسه نمونه آزمایش'),
        ),
        migrations.RemoveField(
            model_name='temporarytestinfo',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='temporarytestinfo',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='temporarytestinfo',
            name='test',
        ),
        migrations.RemoveField(
            model_name='temporarytestinfo',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='discountinfo',
            options={'verbose_name': 'اطلاعات تخفیف', 'verbose_name_plural': 'اطلاعات تخفیف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'درخواست', 'verbose_name_plural': 'درخواست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='requestinfo',
            options={'verbose_name': 'اطلاعات درخواست', 'verbose_name_plural': 'اطلاعات درخواست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'verbose_name': 'اطلاعات نمونه', 'verbose_name_plural': 'اطلاعات نمونه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='testinfo',
            options={'verbose_name': 'اطلاعات آزمایش', 'verbose_name_plural': 'اطلاعات آزمایش\u200cها'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_pdf',
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='is_perishable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه فاسدشدنی است'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_return',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه برگشت داده شده بشود'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='storage_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='storage_duration_unit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='واحد مدت زمان نگهداری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('successful', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='LaboratoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد سفارش')),
                ('submission_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع نمونه')),
                ('customer_sample_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام نمونه مشتری')),
                ('sample_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نمونه')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('is_perishable', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه فاسدشدنی است')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('sample_return', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه برگشت داده شده بشود')),
                ('storage_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)')),
                ('storage_duration_unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='واحد مدت زمان نگهداری')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='شرایط نگهداری')),
                ('sample_description', models.TextField(blank=True, null=True, verbose_name='توضیحات نمونه')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='sample_files/', verbose_name='فایل تکمیلی نمونه')),
                ('user_sample', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه نمونه آزمایش')),
                ('repeat_count_test', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تکرار آزمون')),
                ('parameter_values', models.JSONField(verbose_name='مقادیر پارامتر')),
                ('is_faculty_member', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا کاربر عضو هیات علمی است؟')),
                ('is_student_or_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا کاربر دانشجو یا کارکنان دانشگاه است؟')),
                ('is_affiliated_with_institution', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا کاربر متقاضی استفاده از تخفیف نهادهای طرف قرارداد است؟')),
                ('discount_institution_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام نهاد تخفیف')),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='تکمیل شده')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='پیش فاکتور')),
                ('status', models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('successful', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده'), ('ready_for_payment', 'آماده پرداخت')], default='pending', max_length=20, null=True, verbose_name='وضعیت')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.experiment', verbose_name='آزمایش')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.parameters', verbose_name='پارامتر')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.test', verbose_name='عنوان آزمایش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryDiscountInfo',
        ),
        migrations.DeleteModel(
            name='TemporaryOrder',
        ),
        migrations.DeleteModel(
            name='TemporaryRequestInfo',
        ),
        migrations.DeleteModel(
            name='TemporarySampleInfo',
        ),
        migrations.DeleteModel(
            name='TemporaryTestInfo',
        ),
    ]
