# Generated by Django 5.1.1 on 2025-01-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountinfo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sampleinfo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="testinfo",
            options={},
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="is_perishable",
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="sample_return",
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="storage_duration",
        ),
        migrations.RemoveField(
            model_name="sampleinfo",
            name="storage_duration_unit",
        ),
        migrations.RemoveField(
            model_name="testinfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="testinfo",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="invoices/", verbose_name="پیش فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_info",
                to="orders.order",
            ),
        ),
    ]
