# Generated by Django 5.0.4 on 2024-09-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_requestinfo_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='AdditionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='ExperimentInfo',
            new_name='experimentinfo',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='RequestInfo',
            new_name='requestinfo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='SampleInfo',
        ),
        migrations.AddField(
            model_name='request',
            name='sample_info',
            field=models.ManyToManyField(related_name='requests', to='orders.sampleinfo', verbose_name='اطلاعات نمونه'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sample_infos', to='orders.request', verbose_name='درخواست'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TemporaryRequest',
        ),
    ]
