# Generated by Django 5.1.1 on 2025-01-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_final_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default=1, max_length=255, verbose_name='Tracking Code'),
            preserve_default=False,
        ),
    ]
