# Generated by Django 5.1.1 on 2025-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tracking Code"
            ),
        ),
    ]
