# Generated by Django 5.1.1 on 2025-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_step',
            field=models.PositiveIntegerField(default=1, verbose_name='مرحله جاری'),
        ),
    ]
