# Generated by Django 5.1.1 on 2025-01-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_current_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال بررسی"),
                    ("successful", "پرداخت موفق"),
                    ("failed", "پرداخت ناموفق"),
                    ("canceled", "لغو شده"),
                    ("ready_for_payment", "آماده پرداخت"),
                    ("incomplete", "تکمیل نشده"),
                ],
                default="incomplete",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
