# Generated by Django 5.0.4 on 2024-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sampleinfo_sample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleinfo',
            name='sample_amount',
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد نمونه'),
            preserve_default=False,
        ),
    ]
