# Generated by Django 5.0.4 on 2024-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_sampleinfo_sample_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleinfo',
            old_name='sample_name',
            new_name='customer_sample_name',
        ),
        migrations.RenameField(
            model_name='sampleinfo',
            old_name='storage_unit',
            new_name='storage_duration_unit',
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='sample_files/', verbose_name='فایل تکمیلی نمونه'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات نمونه'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='شرایط نگهداری'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='storage_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)'),
        ),
    ]
