# Generated by Django 5.0.4 on 2024-09-30 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_sample_name_sampleinfo_customer_sample_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='customer_sample_name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام نمونه مشتری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='is_perishable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه فاسدشدنی است'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_return',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه برگشت داده شده بشود'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_unit',
            field=models.CharField(blank=True, choices=[('KG', 'کیلوگرم'), ('G', 'گرم'), ('MG', 'میلی\u200cگرم'), ('LB', 'پوند'), ('OZ', 'اونس')], max_length=50, null=True, verbose_name='واحد اندازه\u200cگیری'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='storage_duration_unit',
            field=models.CharField(blank=True, choices=[('D', 'روز'), ('W', 'هفته'), ('M', 'ماه')], max_length=10, null=True, verbose_name='واحد مدت زمان نگهداری'),
        ),
    ]
