# Generated by Django 5.0.4 on 2024-10-10 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_testinformation_sample_and_more'),
        ('services', '0026_sample_is_returnable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestInformation',
            new_name='TestInfo',
        ),
    ]
