# Generated by Django 5.0.4 on 2024-10-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_rename_requestinfo_request_request_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='test_info',
        ),
        migrations.AddField(
            model_name='request',
            name='test_info',
            field=models.ManyToManyField(to='orders.testinfo', verbose_name='اطلاعات آزمایش'),
        ),
    ]
