# Generated by Django 5.0.4 on 2024-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_laboratoryrequest_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
