# Generated by Django 5.1.1 on 2024-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_laboratoryrequest_tracking_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testinfo",
            name="parameter_value",
        ),
        migrations.AddField(
            model_name="testinfo",
            name="parameter_values",
            field=models.JSONField(default=1, verbose_name="مقادیر پارامتر"),
            preserve_default=False,
        ),
    ]
