# Generated by Django 5.1.1 on 2024-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0042_remove_testinfo_parameter_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testinfo",
            name="parameter_values",
            field=models.JSONField(
                blank=True, null=True, verbose_name="مقادیر پارامتر"
            ),
        ),
    ]
