# Generated by Django 5.1.1 on 2024-12-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0045_remove_laboratoryrequest_parameter_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountinfo",
            name="contract_party_file",
            field=models.FileField(
                blank=True, null=True, upload_to="contract_party_files/"
            ),
        ),
        migrations.AddField(
            model_name="discountinfo",
            name="has_labs_net_grant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discountinfo",
            name="has_research_grant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discountinfo",
            name="labs_net_file",
            field=models.FileField(blank=True, null=True, upload_to="labs_net_files/"),
        ),
        migrations.AddField(
            model_name="discountinfo",
            name="research_grant_withdrawal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="discountinfo",
            name="send_cost",
            field=models.BooleanField(default=False),
        ),
    ]
