# Generated by Django 5.1.1 on 2024-12-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0046_discountinfo_contract_party_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountinfo",
            name="discount_institution_name",
        ),
    ]
