# Generated by Django 5.1.1 on 2024-12-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0047_remove_discountinfo_discount_institution_name"),
        ("services", "0035_rename_value_parametervalue_default_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountinfo",
            options={
                "verbose_name": "اطلاعات تخفیف",
                "verbose_name_plural": "اطلاعات تخفیف\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="laboratoryrequest",
            options={
                "verbose_name": "درخواست آزمایشگاهی",
                "verbose_name_plural": "درخواست\u200cهای آزمایشگاهی",
            },
        ),
        migrations.AlterModelOptions(
            name="request",
            options={
                "verbose_name": "درخواست",
                "verbose_name_plural": "درخواست\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="requestinfo",
            options={
                "verbose_name": "اطلاعات درخواست",
                "verbose_name_plural": "اطلاعات درخواست\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="sampleinfo",
            options={
                "verbose_name": "اطلاعات نمونه",
                "verbose_name_plural": "اطلاعات نمونه\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="testinfo",
            options={
                "verbose_name": "اطلاعات آزمایش",
                "verbose_name_plural": "اطلاعات آزمایش\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="contract_party_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contract_party_files/",
                verbose_name="فایل نهاد تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.experiment",
                verbose_name="آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="has_labs_net_grant",
            field=models.BooleanField(
                default=False, verbose_name="آیا کاربر دارای گرنت شبکه آزمایشگاهی است؟"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="has_research_grant",
            field=models.BooleanField(
                default=False, verbose_name="آیا کاربر دارای گرنت پژوهشی است؟"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="is_affiliated_with_institution",
            field=models.BooleanField(
                default=False,
                verbose_name="آیا کاربر متقاضی استفاده از تخفیف نهادهای طرف قرارداد است؟",
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="is_faculty_member",
            field=models.BooleanField(
                default=False, verbose_name="آیا کاربر عضو هیات علمی است؟"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="is_student_or_staff",
            field=models.BooleanField(
                default=False, verbose_name="آیا کاربر دانشجو یا کارکنان دانشگاه است؟"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="labs_net_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="labs_net_files/",
                verbose_name="فایل گرنت شبکه آزمایشگاهی",
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="research_grant_withdrawal_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="میزان استفاده از گرنت پژوهشی"
            ),
        ),
        migrations.AlterField(
            model_name="discountinfo",
            name="send_cost",
            field=models.BooleanField(
                default=False, verbose_name="تمایل به پرداخت هزینه ارسال"
            ),
        ),
        migrations.AlterField(
            model_name="laboratoryrequest",
            name="tracking_code",
            field=models.CharField(max_length=255, verbose_name="کد پیگیری"),
        ),
        migrations.AlterField(
            model_name="request",
            name="is_complete",
            field=models.BooleanField(default=False, verbose_name="تکمیل شده"),
        ),
        migrations.AlterField(
            model_name="requestinfo",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.experiment",
                verbose_name="آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="sampleinfo",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.experiment",
                verbose_name="آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="testinfo",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.experiment",
                verbose_name="آزمایش",
            ),
        ),
    ]
