# Generated by Django 5.1.1 on 2024-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_alter_discountinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryrequest',
            name='discount_institution_name',
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='contract_party_file',
            field=models.FileField(blank=True, null=True, upload_to='contract_party_files/', verbose_name='فایل نهاد تخفیف'),
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='has_labs_net_grant',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر دارای گرنت شبکه آزمایشگاهی است؟'),
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='has_research_grant',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر دارای گرنت پژوهشی است؟'),
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='labs_net_file',
            field=models.FileField(blank=True, null=True, upload_to='labs_net_files/', verbose_name='فایل گرنت شبکه آزمایشگاهی'),
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='research_grant_withdrawal_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='میزان استفاده از گرنت پژوهشی'),
        ),
        migrations.AddField(
            model_name='laboratoryrequest',
            name='send_cost',
            field=models.BooleanField(default=False, verbose_name='تمایل به پرداخت هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='is_affiliated_with_institution',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر متقاضی استفاده از تخفیف نهادهای طرف قرارداد است؟'),
        ),
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='is_faculty_member',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر عضو هیات علمی است؟'),
        ),
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='is_student_or_staff',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر دانشجو یا کارکنان دانشگاه است؟'),
        ),
    ]
