# Generated by Django 5.1.1 on 2024-12-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_remove_laboratoryrequest_discount_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratoryrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requestinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='is_perishable',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='sample_return',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='storage_duration',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='storage_duration_unit',
        ),
    ]
