# Generated by Django 5.1.1 on 2024-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_discountinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='parameter_values',
            field=models.JSONField(blank=True, null=True, verbose_name='مقادیر پارامتر'),
        ),
    ]
