# Generated by Django 5.1.1 on 2025-01-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_hyperlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="hyperlink",
            name="display_option",
            field=models.BooleanField(default=True),
        ),
    ]
