# Generated by Django 5.0.4 on 2024-08-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_banner_remove_homepage_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banners',
        ),
    ]
