# Generated by Django 5.1.1 on 2024-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_banners_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="bottom_text",
            field=models.TextField(max_length=197, verbose_name="متن پایین صفحه"),
        ),
    ]
