# Generated by Django 5.1.1 on 2024-12-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_alter_homepage_bottom_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banners",
            name="description",
        ),
        migrations.RemoveField(
            model_name="banners",
            name="title",
        ),
    ]
