# Generated by Django 5.0.4 on 2024-09-01 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to='services_images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه ها',
                'ordering': ['-created_date'],
            },
        ),
    ]
