# Generated by Django 5.0.4 on 2024-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['brand'], 'verbose_name': 'دستگاه', 'verbose_name_plural': 'دستگاه ها'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='content',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='title',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='device',
            name='additional_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(default=523, max_length=255, verbose_name='برند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='services_description',
            field=models.TextField(default=45, verbose_name='شرح خدمات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='usage',
            field=models.CharField(default=54, max_length=255, verbose_name='کاربرد'),
            preserve_default=False,
        ),
    ]
