# Generated by Django 5.0.4 on 2024-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options_remove_device_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=11, max_length=255, verbose_name='نام دستگاه'),
            preserve_default=False,
        ),
    ]
