# Generated by Django 5.1.1 on 2024-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_options_remove_device_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="usage",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کاربرد"
            ),
        ),
    ]
