# Generated by Django 5.1.1 on 2024-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_device_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="display_option",
            field=models.CharField(
                choices=[
                    ("show", "نمایش در صفحه اصلی"),
                    ("hide", "عدم نمایش در صفحه اصلی"),
                ],
                default="show",
                max_length=4,
                verbose_name="گزینه نمایش",
            ),
        ),
    ]
