# Generated by Django 5.1.1 on 2024-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_device_display_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="services_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="device",
            name="additional_details",
        ),
    ]
