# Generated by Django 5.1.1 on 2024-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_rename_services_description_device_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="device",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="مدل دستگاه"
            ),
        ),
    ]
