# Generated by Django 5.1.1 on 2024-12-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_alter_device_description_alter_device_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="usage",
        ),
        migrations.AddField(
            model_name="device",
            name="capabilities",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="قابلیت ها"
            ),
        ),
    ]
