# Generated by Django 5.1.1 on 2024-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_remove_device_usage_device_capabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="capabilities",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="قابلیت ها"
            ),
        ),
    ]
