# Generated by Django 5.0.7 on 2024-08-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('aboutuspage_image', models.ImageField(blank=True, null=True, upload_to='aboutus/', verbose_name='تصویر صفحه درباره ما ')),
                ('content', models.TextField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='تیتر صفحه اصلی')),
                ('top_text', models.TextField(verbose_name='متن بالای صفحه')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='بنر صفحه اصلی')),
                ('aboutـtitle', models.CharField(max_length=255, verbose_name='تیتر  درباره ما صفحه اصلی')),
                ('about_text', models.TextField(verbose_name=' متن درباره صفحه اصلی')),
                ('aboutـbanner', models.ImageField(upload_to='banners/', verbose_name=' بنر در باره ما صفحه اصلی')),
                ('bottom_text', models.TextField(verbose_name='متن پایین صفحه')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'خبرنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('Sat', 'شنبه'), ('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهار شنبه'), ('Thu', 'پنج شنبه'), ('Fri', 'جمعه')], max_length=3, verbose_name='روز شروع')),
                ('end_day', models.CharField(choices=[('Sat', 'شنبه'), ('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهار شنبه'), ('Thu', 'پنج شنبه'), ('Fri', 'جمعه')], max_length=3, verbose_name='روز پایان')),
                ('start_time', models.CharField(max_length=256, verbose_name='زمان شروع')),
                ('end_time', models.CharField(max_length=256, verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'ساعات کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='تلفن همراه')),
                ('landline_phone', models.CharField(max_length=15, verbose_name='تلفن ثابت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram ID')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='whatsapp ')),
                ('workingHour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.workinghour', verbose_name='ساعت کاری')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
