# Generated by Django 5.0.4 on 2024-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contact_whatsapp_alter_contact_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='تیتر بنر')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='top_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.ManyToManyField(related_name='HomePage', to='website.banner', verbose_name='بنر ها'),
        ),
    ]
