# Generated by Django 5.0.4 on 2024-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(default=1, max_length=255, verbose_name='Tracking Code'),
            preserve_default=False,
        ),
    ]
