# Generated by Django 5.0.4 on 2024-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=9, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
