# Generated by Django 5.0.4 on 2024-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
