# Generated by Django 5.0.4 on 2024-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=10, null=True),
        ),
    ]
