# Generated by Django 5.0.4 on 2024-09-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_laboratory_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameter',
            new_name='Parameters',
        ),
    ]
