# Generated by Django 5.0.4 on 2024-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_experiment_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='unit_type',
        ),
    ]
