# Generated by Django 5.0.4 on 2024-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_remove_test_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_returnable',
            field=models.BooleanField(default=False, verbose_name='نمونه برگشت پذیر است؟'),
        ),
    ]
