# Generated by Django 5.0.4 on 2024-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_sample_is_returnable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitamount',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
