# Generated by Django 5.1.1 on 2024-12-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_alter_experiment_options_alter_faculty_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameters",
            name="laboratory",
        ),
    ]
