# Generated by Django 5.1.1 on 2024-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0032_parametervalue_parameters_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametervalue",
            name="max_value",
            field=models.FloatField(blank=True, null=True, verbose_name="حداکثر مقدار"),
        ),
        migrations.AddField(
            model_name="parametervalue",
            name="min_value",
            field=models.FloatField(blank=True, null=True, verbose_name="حداقل مقدار"),
        ),
        migrations.AlterField(
            model_name="parametervalue",
            name="value",
            field=models.CharField(
                default="Default Value", max_length=255, verbose_name="مقدار"
            ),
        ),
    ]
