# Generated by Django 5.1.1 on 2024-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_alter_parametervalue_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametervalue",
            old_name="value",
            new_name="default_value",
        ),
        migrations.AddField(
            model_name="parametervalue",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="نام مقدار"),
            preserve_default=False,
        ),
    ]
