# Generated by Django 5.0.4 on 2024-09-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('userpanel', '0002_alter_test_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='devices.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='location',
            field=models.CharField(choices=[('SD', 'صدرا'), ('SH', 'شیراز')], max_length=2),
        ),
    ]
