# Generated by Django 5.0.4 on 2024-09-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('SD', 'صدرا'), ('SH', 'شیراز')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('SD', 'صدرا'), ('SH', 'شیراز')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('iso_17025', models.CharField(choices=[('has', 'دارد'), ('has_not', 'ندارد')], default='has_not', max_length=7, verbose_name='ISO 17025')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=8)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='devices.device')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='accounts.profile')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='services.faculty')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='services.laboratory')),
            ],
        ),
    ]
