# Generated by Django 5.0.4 on 2024-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='تعرفه آزاد'),
            preserve_default=False,
        ),
    ]
