# Generated by Django 5.0.4 on 2024-08-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
