# Generated by Django 5.0.4 on 2024-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_experiment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='technical_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مدیر فنی'),
        ),
    ]
