# Generated by Django 5.0.4 on 2024-09-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_laboratory_technical_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='location',
        ),
    ]
