# Generated by Django 5.0.4 on 2024-09-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_experiment_experiment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSpecification',
            new_name='Tests',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='test_specifications',
            new_name='tests',
        ),
    ]
