# Generated by Django 5.0.4 on 2024-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_experiment_test_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit_amount',
            new_name='UnitAmount',
        ),
        migrations.RenameModel(
            old_name='Unit_price',
            new_name='UnitPrice',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='tests',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام فارسی آزمون')),
                ('name_en', models.CharField(max_length=255, verbose_name='نام انگلیسی آزمون')),
                ('unit_type', models.CharField(choices=[('EQ', 'دستگاه'), ('CM', 'کامپیوتر'), ('MA', 'ماشین')], max_length=2, verbose_name='نوع واحد آزمون')),
                ('operating_range', models.TextField(verbose_name='گستره کاری')),
                ('description', models.TextField(verbose_name='توصیف آزمون')),
                ('standards', models.ManyToManyField(related_name='tests', to='services.standards', verbose_name='استانداردها')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='tests',
            field=models.ManyToManyField(related_name='samples', to='services.test', verbose_name='آزمون\u200cها'),
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
