# Generated by Django 5.0.4 on 2024-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_unitamount_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
