# Generated by Django 5.0.4 on 2024-09-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('customer_code', models.CharField(max_length=20, verbose_name='کد مشتری')),
                ('request_type', models.CharField(max_length=50, verbose_name='نوع درخواست')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=255, verbose_name='نوع نمونه')),
                ('sample_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار نمونه')),
                ('sample_unit', models.CharField(choices=[('C', 'سانتی گراد'), ('F', 'فارنهایت'), ('K', 'کلوین')], max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='requests.request', verbose_name='درخواست')),
            ],
        ),
    ]
