# Generated by Django 5.0.4 on 2024-09-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_request_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='customer_code',
        ),
    ]
