# Generated by Django 5.0.4 on 2024-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_request_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_unit',
            field=models.CharField(choices=[('C', 'سانتی گراد'), ('F', 'فارنهایت'), ('K', 'کلوین'), ('H', 'ساعت'), ('MIN', 'دقیقه'), ('S', 'ثانیه')], max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
