# Generated by Django 5.0.4 on 2024-09-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_sample_sample_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_return', models.BooleanField(default=False, verbose_name='نمونه برگشت داده شده بشود')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faculty_member', models.BooleanField(default=False)),
                ('is_student_or_staff', models.BooleanField(default=False)),
                ('is_affiliated_with_institution', models.BooleanField(default=False)),
                ('discount_institution_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='نمونه فاسدشدنی است'),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_unit',
            field=models.CharField(choices=[('D', 'روز'), ('W', 'هفته'), ('M', 'ماه')], default=1, max_length=10, verbose_name='واحد مدت زمان نگهداری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('vacuum_oven', 'Vacuum Oven'), ('oven', 'Oven'), ('sieve_sample', 'نمونه دانه بندی (الک)')], max_length=50, verbose_name='نوع نمونه'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_unit',
            field=models.CharField(choices=[('KG', 'کیلوگرم'), ('G', 'گرم'), ('MG', 'میلی\u200cگرم'), ('LB', 'پوند'), ('OZ', 'اونس')], max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='requests.cost', verbose_name='درخواست')),
                ('discountInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='requests.discountinfo', verbose_name='درخواست')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='requests.additionalinfo', verbose_name='اطلاعات اضافی')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='requests.cost', verbose_name='هزینه')),
                ('discount_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='requests.discountinfo', verbose_name='تخفیف')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='ExperimentInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.experimentinfo', verbose_name='اطلاعات آزمایش'),
        ),
    ]
