# Generated by Django 5.0.4 on 2024-09-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
        ('requests', '0005_cost_discountinfo_sample_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('vacuum_oven', 'Vacuum Oven'), ('oven', 'Oven'), ('sieve_sample', 'نمونه دانه بندی (الک)')], max_length=50, verbose_name='نوع نمونه')),
                ('sample_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار نمونه')),
                ('sample_unit', models.CharField(choices=[('KG', 'کیلوگرم'), ('G', 'گرم'), ('MG', 'میلی\u200cگرم'), ('LB', 'پوند'), ('OZ', 'اونس')], max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='نمونه فاسدشدنی است')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('storage_duration', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)')),
                ('storage_unit', models.CharField(choices=[('D', 'روز'), ('W', 'هفته'), ('M', 'ماه')], max_length=10, verbose_name='واحد مدت زمان نگهداری')),
            ],
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='discountInfo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='AdditionalInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.additionalinfo', verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50, verbose_name='نوع درخواست')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='RequestInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.requestinfo', verbose_name='اطلاعات درخواست'),
        ),
        migrations.AddField(
            model_name='request',
            name='SampleInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.sampleinfo', verbose_name='اطلاعات نمونه'),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
