# Generated by Django 5.0.4 on 2024-09-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_sampleinfo_remove_additionalinfo_discountinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinfo',
            name='request_type',
        ),
    ]
