# Generated by Django 5.0.4 on 2024-09-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_test_device_alter_laboratory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='test',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='test',
            name='device',
        ),
        migrations.RemoveField(
            model_name='test',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
