# Generated by Django 5.0.4 on 2024-09-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
        ('orders', '0001_initial'),
        ('services', '0024_remove_experiment_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinfo',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='experimentinfo',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='experimentinfo',
            name='discount_info',
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='experiment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_return',
            field=models.BooleanField(default=False, verbose_name='نمونه برگشت داده شده بشود'),
        ),
        migrations.CreateModel(
            name='TemporaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('sample_info', models.JSONField(default=dict, verbose_name='اطلاعات نمونه')),
                ('experiment_info', models.JSONField(default=dict, verbose_name='اطلاعات آزمایش')),
                ('additional_info', models.JSONField(default=dict, verbose_name='اطلاعات تکمیلی')),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
