# Generated by Django 5.0.4 on 2024-09-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_sampleinfo_storage_duration_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleinfo',
            name='request',
        ),
    ]
