# Generated by Django 5.0.4 on 2024-10-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_sampleinfo_sample_unit'),
        ('services', '0026_sample_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinformation',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.parameters', verbose_name='پارامتر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinformation',
            name='parameter_value',
            field=models.CharField(default=1, max_length=255, verbose_name='مقدار پارامتر'),
            preserve_default=False,
        ),
    ]
