# Generated by Django 5.0.4 on 2024-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='پیش فاکتور'),
        ),
    ]
