# Generated by Django 5.0.4 on 2024-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_request_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
