# Generated by Django 5.0.4 on 2024-10-12 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_request_is_complete'),
        ('services', '0028_alter_parameters_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('sample_type', models.CharField(max_length=50, verbose_name='نوع نمونه')),
                ('customer_sample_name', models.CharField(max_length=255, verbose_name='نام نمونه مشتری')),
                ('sample_count', models.PositiveIntegerField(verbose_name='تعداد نمونه')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('is_perishable', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه فاسدشدنی است')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('sample_return', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمونه برگشت داده شده بشود')),
                ('storage_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان نگهداری (به روز)')),
                ('storage_duration_unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='واحد مدت زمان نگهداری')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='شرایط نگهداری')),
                ('sample_description', models.TextField(blank=True, null=True, verbose_name='توضیحات نمونه')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='sample_files/', verbose_name='فایل تکمیلی نمونه')),
                ('user_sample', models.CharField(blank=True, max_length=255, verbose_name='شناسه نمونه آزمایش')),
                ('repeat_count_test', models.PositiveIntegerField(verbose_name='تعداد تکرار آزمون')),
                ('parameter_value', models.CharField(max_length=255, verbose_name='مقدار پارامتر')),
                ('is_faculty_member', models.BooleanField(default=False, verbose_name='آیا کاربر عضو هیات علمی است؟')),
                ('is_student_or_staff', models.BooleanField(default=False, verbose_name='آیا کاربر دانشجو یا کارکنان دانشگاه است؟')),
                ('is_affiliated_with_institution', models.BooleanField(default=False, verbose_name='آیا کاربر متقاضی استفاده از تخفیف نهادهای طرف قرارداد است؟')),
                ('discount_institution_name', models.CharField(blank=True, max_length=255, verbose_name='نام نهاد تخفیف')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.experiment', verbose_name='آزمایش')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.parameters', verbose_name='پارامتر')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.test', verbose_name='عنوان آزمایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
