# Generated by Django 5.0.4 on 2024-10-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_requestinfo_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryrequest',
            name='order_code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='کد سفارش'),
        ),
    ]
