# Generated by Django 5.0.4 on 2024-10-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_laboratoryrequest_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='invoice_pdf',
        ),
    ]
