# Generated by Django 5.0.4 on 2024-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_request_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='order_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد سفارش'),
        ),
    ]
