# Generated by Django 5.0.4 on 2024-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_laboratoryrequest_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('successful', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده'), ('ready_for_payment', 'آماده پرداخت')], default='pending', max_length=20, null=True, verbose_name='وضعیت'),
        ),
    ]
