# Generated by Django 5.1.1 on 2024-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="display_option",
            field=models.CharField(
                choices=[
                    ("show", "نمایش در صفحه اصلی"),
                    ("hide", "عدم نمایش در صفحه اصلی"),
                ],
                default="show",
                max_length=4,
                verbose_name="گزینه نمایش",
            ),
        ),
    ]
